// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDriNNn5zq1MhlVpTM-db8KbEhv5ITeO3Y',
    appId: '1:965328670840:web:4a80ea993e526f46f6dd8d',
    messagingSenderId: '965328670840',
    projectId: 'location-tracker-app-a109e',
    authDomain: 'location-tracker-app-a109e.firebaseapp.com',
    storageBucket: 'location-tracker-app-a109e.firebasestorage.app',
    measurementId: 'G-FPP8D10BY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCynk2DoZOeW1xh7yjd-iUFRo8QRX8y_IE',
    appId: '1:965328670840:android:6c85b1c80f65418cf6dd8d',
    messagingSenderId: '965328670840',
    projectId: 'location-tracker-app-a109e',
    storageBucket: 'location-tracker-app-a109e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Cbjch0KQUVuK5trTBhmWiLvxFfVpix0',
    appId: '1:965328670840:ios:d8b3f67df7330c6df6dd8d',
    messagingSenderId: '965328670840',
    projectId: 'location-tracker-app-a109e',
    storageBucket: 'location-tracker-app-a109e.firebasestorage.app',
    iosClientId: '965328670840-3ulfqleu1jrvulb0miqan0ti732ou521.apps.googleusercontent.com',
    iosBundleId: 'com.example.locationTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Cbjch0KQUVuK5trTBhmWiLvxFfVpix0',
    appId: '1:965328670840:ios:d8b3f67df7330c6df6dd8d',
    messagingSenderId: '965328670840',
    projectId: 'location-tracker-app-a109e',
    storageBucket: 'location-tracker-app-a109e.firebasestorage.app',
    iosClientId: '965328670840-3ulfqleu1jrvulb0miqan0ti732ou521.apps.googleusercontent.com',
    iosBundleId: 'com.example.locationTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDriNNn5zq1MhlVpTM-db8KbEhv5ITeO3Y',
    appId: '1:965328670840:web:9f0cdd801a15950df6dd8d',
    messagingSenderId: '965328670840',
    projectId: 'location-tracker-app-a109e',
    authDomain: 'location-tracker-app-a109e.firebaseapp.com',
    storageBucket: 'location-tracker-app-a109e.firebasestorage.app',
    measurementId: 'G-2FH827VS7M',
  );
}
